# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  repositoryName: '$(dockerId).azurecr.io/microsoft/ruby-on-azure'
  imageName: '$(repositoryName):$(build.buildId)'
  latest: '$(repositoryName):latest'

steps:
- script: |
    docker login -u $(dockerId) -p $pswd $(dockerid).azurecr.io
    docker pull $(latest)
    docker build -f Dockerfile --cache-from $(latest) -t $(imageName) -t $(latest) .
    docker push $(imageName)
    docker push $(latest)
  env:
    pswd: $(dockerPassword)